services:
  zookeeper_svc:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper_cntr
    hostname: zookeeper_host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - "2181:2181"
    restart: always
    networks:
    - jojonomic-test-net

  kafka_svc:
    image: confluentinc/cp-kafka
    container_name: kafka_cntr
    hostname: kafka_host
    depends_on:
    - zookeeper_svc
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_svc:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_svc:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - "29092:29092"
    - "9092:9092"
    restart: always
    networks:
    - jojonomic-test-net

networks:
  jojonomic-test-net:
    external: true