services:
  postgres_svc:
    image: postgres:15.1-bullseye
    container_name: postgres_cntr
    hostname: postgres_host
    restart: always
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: "87654321"
      POSTGRES_DB: jojonomic_test
      TZ: UTC
      PGTZ: UTC
    ports:
    - 5432:5432
    networks:
    - jojonomic-test-net
    volumes:
    - jojonomic-test-pgdata-vol:/var/lib/postgres/data
    - jojonomic-test-pgmigrations-vol:/var/lib/postgres/migrations
    - /mnt/c/Users/milha/Home/jojonomic-test/misc/postgres_migrations.sh:/docker-entrypoint-initdb.d/postgres_migrations.sh

networks:
  jojonomic-test-net:
    external: true

volumes:
  jojonomic-test-pgdata-vol:
    external: true
  jojonomic-test-pgmigrations-vol:
    external: true